routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@login')->name("login");

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('profesores','ProfesorController');
Route::resource('grados','GradoController');
Route::resource('alumnos','AlumnoController');
Route::resource('bloques','BloqueController');
Route::resource('calificaciones','CalificacionController');
Route::post('calificaciones/delete','CalificacionController@delete')->name('deleteCalificaciones');

resources/views/admin/calificaciones/add.blade.php
@extends('layouts.master')
@section('title','Calificaciones')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Agregar Calificacion</h1>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('calificaciones.store') }}">
            {{ csrf_field() }}
            <div class="row">
              <div class="form-group col-md-6">
                <label for="foto">Alumno:</label>
                <select name="alumno_id" id="alumno_id" class="form-control">
                  @empty(!$alumnos)
                  @foreach ($alumnos as $a)
                  <option value="{{$a->id}}">{{$a->nombre_completo}}</option>
                  @endforeach
                  @endempty

                </select>
              </div>
              <div class="form-group col-md-6">
                <label for="foto">Bloque:</label>
                <select name="bloque_id" id="bloque_id" class="form-control">
                  @empty(!$bloques)
                  @foreach ($bloques as $b)
                  <option value="{{$b->id}}">{{$b->nombre}}</option>
                  @endforeach
                  @endempty

                </select>
              </div>
            </div>
            <div class="row">

              <div class="form-group col-md-6">
                <label for="calificacion">Calificacion</label>
                <input type="text" class="form-control" name="calificacion" id="calificacion" value="{{ old('calificacion') }}">
              </div>

            </div>
            <button type="submit" class="btn btn-primary">Guardar Calificacion</button>
            <a href="{{ route('calificaciones.index') }}" class="btn btn-link">Regresar al listado de
              calificaciones</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/calificaciones/edit.blade.php
@extends('layouts.master')
@section('title','Calificaciones')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Editar Calificacion</h1>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('calificaciones.update',$calificacion->id) }}">
            {{ method_field('PUT')}}
            {{ csrf_field() }}
            <div class="row">
              <div class="form-group col-md-6">
                <label for="foto">Alumno:</label>
                <select name="alumno_id" id="alumno_id" class="form-control">
                  @empty(!$alumnos)
                  @foreach ($alumnos as $a)

                  <option value="{{$a->id}}" {{($calificacion->alumno_id == $a->id)?'selected':''}}>{{$a->nombre_completo}}
                  </option>

                  @endforeach
                  @endempty

                </select>
              </div>

              <div class="form-group col-md-6">
                <label for="foto">Bloque:</label>
                <select name="bloque_id" id="bloque_id" class="form-control">
                  @empty(!$bloques)
                  @foreach ($bloques as $b)

                  <option value="{{$b->id}}" {{($calificacion->bloque_id == $b->id)?'selected':''}}>{{$b->nombre}}
                  </option>

                  @endforeach
                  @endempty

                </select>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="calificacion">Calificacion</label>
                <input type="text" class="form-control" name="calificacion" id="calificacion" value="{{ old('calificacion',$calificacion->calificacion) }}">
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Editar Calificacion</button>
            <a href="{{ route('calificaciones.index') }}" class="btn btn-link">Regresar al listado de
              calificaciones</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/calificaciones/index.blade.php
@extends('layouts.master')
@section('title','Calificaciones')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Listado de calificaciones</h1>
          calificaciones |
          Página
          {{$calificaciones->currentPage()}}
          de
          {{$calificaciones->lastPage()}}
        </div>
        <div class="card-body">
          <h1 class="text-center text-primary"></h1>
          <a class="btn btn-primary my-2" href="{{route('calificaciones.create')}}">Agregar Calificacion a alumno
          </a>
          <form action="{{route('deleteCalificaciones')}}" method="POST">
            {{ csrf_field() }}
            <button class="btn btn-danger my-2" type="submit">Eliminar Calificaciones<span
              class="mdi mdi-plus"></span></button>
          </form>

          <table class="table table-hover table-striped table-bordered table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Calificacion</th>
                <th scope="col">Alumno</th>
                <th scope="col">Bloque</th>
                <th scope="col" colspan="2" class="text-center">Opciones</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($calificaciones as $cal)
              <tr class="text-center">
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{$cal->calificacion}}</td>
                <td>{{$cal->alumno->nombre_completo}}</td>
                <td>{{$cal->bloque->nombre}}</td>
                <td>
                  <a class="btn btn-success mdi mdi-pencil-outline" href="{{route('calificaciones.edit',$cal->id)}}">Editar</a>
                </td>

              </tr>
              @empty
              <h3 class="bg-danger text-white text-center">No hay datos</h3>
              @endforelse

            </tbody>

          </table>
          {{ $calificaciones->links() }}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection