routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@login')->name("login");

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('profesores','ProfesorController');
Route::resource('grados','GradoController');
Route::resource('alumnos','AlumnoController');
Route::resource('bloques','BloqueController');
Route::resource('calificaciones','CalificacionController');
Route::post('calificaciones/delete','CalificacionController@delete')->name('deleteCalificaciones');

resources/views/admin/profesores/add.blade.php
@extends('layouts.master')
@section('title','Profesores')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Agregar Profesor</h1>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('profesores.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
              <div class="form-group col-md-6">
                <label for="nombre_completo">Nombre completo:</label>
                <input type="text" class="form-control" name="nombre_completo" id="nombre_completo"
                  value="{{ old('nombre_completo') }}">
              </div>

              <div class="form-group col-md-6">
                <label for="direccion">Dirección:</label>
                <input type="text" class="form-control" name="direccion" id="direccion" value="{{ old('direccion') }}">
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="telefono">Telefóno:</label>
                <input type="text" class="form-control" name="telefono" id="telefono" value="{{ old('telefono') }}">
              </div>
              <div class="form-group col-md-6">
                <label for="foto">Foto:</label>
                <input type="file" class="form-control" name="foto" id="foto" value="{{ old('foto') }}">
              </div>

            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="foto">Estatus:</label>
                <select name="estatus" id="estatus" class="form-control">
                  <option value="1">Activo</option>
                  <option value="0">Inactivo</option>
                </select>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Crear Profesor</button>
            <a href="{{ route('profesores.index') }}" class="btn btn-link">Regresar al listado de
              profesores</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/profesores/edit.blade.php
@extends('layouts.master')
@section('title','Profesores')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Editar Profesor</h1>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('profesores.update',$profesor->id) }}" enctype="multipart/form-data">
            {{ method_field('PUT')}}
            {{ csrf_field() }}
            <div class="row">
              <div class="form-group col-md-6">
                <label for="nombre_completo">Nombre completo:</label>
                <input type="text" class="form-control" name="nombre_completo" id="nombre_completo"
                  value="{{ old('nombre_completo',$profesor->nombre_completo) }}">
              </div>

              <div class="form-group col-md-6">
                <label for="direccion">Dirección:</label>
                <input type="text" class="form-control" name="direccion" id="direccion"
                  value="{{ old('direccion',$profesor->direccion) }}">
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="telefono">Telefóno:</label>
                <input type="text" class="form-control" name="telefono" id="telefono"
                  value="{{ old('telefono',$profesor->telefono) }}">
              </div>
              <div class="form-group col-md-6">
                <label for="foto">Foto:</label>
                <input type="file" class="form-control" name="foto" id="foto" value="{{ old('foto') }}">
              </div>

            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="foto">Estatus:</label>
                <select name="estatus" id="estatus" class="form-control">
                  @if($profesor->estatus == 1)
                  <option value="1" selected>Activo</option>
                  <option value="0">Inactivo</option>
                  @else
                  <option value="1">Activo</option>
                  <option value="0" selected>Inactivo</option>
                  @endif
                </select>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Editar Profesor</button>
            <a href="{{ route('profesores.index') }}" class="btn btn-link">Regresar al listado de
              profesores</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/profesores/index.blade.php
@extends('layouts.master')
@section('title','Profesores')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Listado de Profesores</h1>
          Profesores |
          Página
          {{$profesores->currentPage()}}
          de
          {{$profesores->lastPage()}}
        </div>
        <div class="card-body">
          <h1 class="text-center text-primary"></h1>
          <a class="btn btn-primary my-2" href="{{route('profesores.create')}}">Agregar Profesor<span
              class="mdi mdi-plus"></span>
          </a>
          <table class="table table-hover table-striped table-bordered table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre Completo</th>
                <th scope="col">Direccion</th>
                <th scope="col">Telefono</th>
                <th scope="col">Estatus</th>
                <th scope="col">Foto</th>
                <th scope="col" colspan="2" class="text-center">Opciones</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($profesores as $pro)
              <tr class="text-center">
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{$pro->nombre_completo}}</td>
                <td>{{$pro->direccion}}</td>
                <td>{{$pro->telefono}}</td>
                <td>{{($pro->estatus == 1)?'Activo':'Inactivo'}}</td>
                <td><img src='{{ asset("fotosProfesor/$pro->foto") }}' style="width:50;height:50px" alt=""></td>
                <td>
                  <a class="btn btn-success mdi mdi-pencil-outline"
                    href="{{route('profesores.edit',$pro->id)}}">Editar</a>
                </td>

              </tr>
              @empty
              <h3 class="bg-danger text-white text-center">No hay datos</h3>
              @endforelse

            </tbody>

          </table>
          {{ $profesores->links() }}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection