routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@login')->name("login");

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('profesores','ProfesorController');
Route::resource('grados','GradoController');
Route::resource('alumnos','AlumnoController');
Route::resource('bloques','BloqueController');
Route::resource('calificaciones','CalificacionController');
Route::post('calificaciones/delete','CalificacionController@delete')->name('deleteCalificaciones');

app/Grado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Grado extends Model
{
    protected $table="grados";
    protected $fillable=[
      'id','nombre','profesor_id'
    ];

    public function profesor(){
      return $this->belongsTo(Profesor::class,'profesor_id');
    }

    public function bloques(){
      return $this->hasMany(Bloque::class);
    }
}

app/Http/Controllers/GradoController.php
<?php

namespace App\Http\Controllers;

use App\Grado;
use App\Profesor;
use Illuminate\Http\Request;
use App\Http\Requests\RequestGrados;

class GradoController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $grados = Grado::paginate(10);
      return view('admin.grados.index',compact('grados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $profesores = Profesor::where('estatus','=','1')->get();
        return view('admin.grados.add',compact('profesores'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RequestGrados $request)
    {
        $datosGrado = $request->except('_token');
        $typealert="success";
        if(Grado::insert($datosGrado)){
          $info="Grado Guardada exitosamente";
        }else{
          $info="Error al Guardar Grado";
          $typealert="danger";
        }

        return back()->with('info',$info)->with('typealert',$typealert);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Grado  $grado
     * @return \Illuminate\Http\Response
     */
    public function show(Grado $grado)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Grado  $grado
     * @return \Illuminate\Http\Response
     */
    public function edit( $id)
    {
      $profesores = Profesor::where('estatus','=','1')->get();
      $grado = Grado::findOrFail($id);
      return view('admin.grados.edit',compact(['grado','profesores']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Grado  $grado
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $datosGrado = $request->except(['_token','_method']);
			$typealert="success";
			if(Grado::where('id','=',$id)->update($datosGrado)){
					$info="Grado Editada exitosamente";
			}else{
					$info="Grado no fue Editado";
					$typealert="danger";
			}

			return back()->with('info',$info)->with('typealert',$typealert);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Grado  $grado
     * @return \Illuminate\Http\Response
     */
    public function destroy(Grado $grado)
    {
        //
    }
}

resources/views/admin/grados/add.blade.php
@extends('layouts.master')
@section('title','Grados')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Agregar Grado</h1>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('grados.store') }}">
            {{ csrf_field() }}
            <div class="row">
              <div class="form-group col-md-6">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" name="nombre" id="nombre" value="{{ old('nombre') }}">
              </div>

              <div class="form-group col-md-6">
                <label for="foto">Profesor:</label>
                <select name="profesor_id" id="profesor_id" class="form-control">
                  @empty(!$profesores)
                  @foreach ($profesores as $p)
                  <option value="{{$p->id}}">{{$p->nombre_completo}}</option>
                  @endforeach
                  @endempty

                </select>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="foto">Estatus:</label>
                <select name="estatus" id="estatus" class="form-control">
                  <option value="1">Activo</option>
                  <option value="0">Inactivo</option>
                </select>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Crear Grado</button>
            <a href="{{ route('grados.index') }}" class="btn btn-link">Regresar al listado de
              grados</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/grados/edit.blade.php
@extends('layouts.master')
@section('title','Grados')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Editar Grado</h1>
        </div>
        <div class="card-body">
          <form method="POST" action="{{ route('grados.update',$grado->id) }}">
            {{ method_field('PUT')}}
            {{ csrf_field() }}
            <div class="row">
              <div class="form-group col-md-6">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" name="nombre" id="nombre"
                  value="{{ old('nombre',$grado->nombre) }}">
              </div>

              <div class="form-group col-md-6">
                <label for="foto">Profesor:</label>
                <select name="profesor_id" id="profesor_id" class="form-control">
                  @empty(!$profesores)
                  @foreach ($profesores as $p)

                  <option value="{{$p->id}}" {{($grado->profesor_id == $p->id)?'selected':''}}>{{$p->nombre_completo}}
                  </option>

                  @endforeach
                  @endempty

                </select>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-6">
                <label for="foto">Estatus:</label>
                <select name="estatus" id="estatus" class="form-control">
                  @if($grado->estatus == 1)
                  <option value="1" selected>Activo</option>
                  <option value="0">Inactivo</option>
                  @else
                  <option value="1">Activo</option>
                  <option value="0" selected>Inactivo</option>
                  @endif
                </select>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Editar Grado</button>
            <a href="{{ route('grados.index') }}" class="btn btn-link">Regresar al listado de
              grados</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/grados/index.blade.php
@extends('layouts.master')
@section('title','Grados')
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h1 class="text-center text-primary">Listado de Grados</h1>
          Grados |
          Página
          {{$grados->currentPage()}}
          de
          {{$grados->lastPage()}}
        </div>
        <div class="card-body">
          <h1 class="text-center text-primary"></h1>
          <a class="btn btn-primary my-2" href="{{route('grados.create')}}">Agregar Grado<span
              class="mdi mdi-plus"></span>
          </a>
          <table class="table table-hover table-striped table-bordered table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre Completo</th>
                <th scope="col">Profesor</th>
                <th scope="col">Estatus</th>
                <th scope="col" colspan="2" class="text-center">Opciones</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($grados as $gra)
              <tr class="text-center">
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{$gra->nombre}}</td>
                <td>{{$gra->profesor->nombre_completo}}</td>
                <td>{{($gra->estatus == 1)?'Activo':'Inactivo'}}</td>
                <td>
                  <a class="btn btn-success mdi mdi-pencil-outline" href="{{route('grados.edit',$gra->id)}}">Editar</a>
                </td>

              </tr>
              @empty
              <h3 class="bg-danger text-white text-center">No hay datos</h3>
              @endforelse

            </tbody>

          </table>
          {{ $grados->links() }}
        </div>
      </div>
    </div>
  </div>
</div>
@endsection